#application.yml

#port
server:
  port: 10090
  
#contextpath
  servlet:
    context-path: /springboot 
    
#view:jsp
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/ 
      suffix: .jsp
#logging
logging:
  level:
    com.kh.spring: DEBUG
    



